/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_GameWindow */

#ifndef _Included_core_GameWindow
#define _Included_core_GameWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_GameWindow
 * Method:    XInitThreads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_core_GameWindow_XInitThreads(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
